### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by iamnewspecies** [TimBeyer/cls-bluebird#20]
We are using Sequeilze which internally uses bluebird. To fix the logging so that it has session id which connects all our logs in one request we added cls-bluebird. But now we are seeing that we are getting "RangeError: Maximum call stack size exceeded" after our application runs for few hours.

What may cause this and is this a know issue?

**Comment by overlookmotel** [comment]
Hi @iamnewspecies.

This is not a known issue. Have you confirmed that this error is due to cls-bluebird? It seems more likely to me that it's not, or that you/Sequelize are using cls-bluebird incorrectly and not exiting contexts after each request. I guess that could result in every request being stacked on top of the last.

Please come back to me when you've investigated further.

**Comment by DavidMorton** [comment]
I just had this same error in production on several servers....

**Comment by DavidMorton** [comment]
bluebird/lib/shimOnCancel.js:41:40)
   at Promise.<anonymous> (/spotv2/spot2/api/node_modules/cls-bluebird/lib/shimOnCancel.js:41:40)
   at Promise.<anonymous> (/spotv2/spot2/api/node_modules/cls-bluebird/lib/shimOnCancel.js:41:40)
   at Promise.<anonymous> (/spotv2/spot2/api/node_modules/cls-bluebird/lib/shimOnCancel.js:41:40)
   at Promise.<anonymous> (/spotv2/spot2/api/node_modules/cls-bluebird/lib/shimOnCancel.js:41:40)
   at Promise.<anonymous> (/spotv2/spot2/api/node_modules/cls-bluebird/lib/shimOnCancel.js:41:40)
   at Promise.<anonymous> (/spotv2/spot2/api/node_modules/cls-bluebird/lib/shimOnCancel.js:41:40)
   at Promise.<anonymous> (/spotv2/spot2/api/node_modules/cls-bluebird/lib/shimOnCancel.js:41:40)
   at Promise.<anonymous> (/spotv2/spot2/api/node_modules/cls-bluebird/lib/shimOnCancel.js:41:40)
   at Promise.<anonymous> (/spotv2/spot2/api/node_modules/cls-bluebird/lib/shimOnCancel.js:41:40)
   at Promise.<anonymous> (/spotv2/spot2/api/node_modules/cls-bluebird/lib/shimOnCancel.js:41:40)
   at Promise.<anonymous> (/spotv2/spot2/api/node_modules/cls-bluebird/lib/shimOnCancel.js:41:40)

**Comment by overlookmotel** [comment]
My apologies. This does sound like it could be an bug in cls-bluebird.

@DavidMorton Can you please share some more details?

* Are you using promise cancellation?
* What version of Node are you running?
* Latest version of cls-bluebird?
* What version of bluebird are you using?
* Any other code you can share

I'll try to get to the bottom of this if I possibly can.

**Comment by charlie-s** [comment]
We're getting this suddenly in production as well. Ex:

```
Unhandled rejection RangeError: Maximum call stack size exceeded
    at executorPatched (/app/node_modules/cls-bluebird/lib/shimOnCancel.js:1:1)
    at executorPatched (/app/node_modules/cls-bluebird/lib/shimOnCancel.js:37:21)
    at executorPatched (/app/node_modules/cls-bluebird/lib/shimOnCancel.js:37:21)
    at executorPatched (/app/node_modules/cls-bluebird/lib/shimOnCancel.js:37:21)
    ...
```

- Node v10.15.2
- Sequelize v5.21.3
- bluebird v3.5.5
- cls-bluebird v2.1.0

We're not using bluebird/cls-bluebird directly at all, but it's a dependency of Sequelize so somewhere under the hood they're using. We're trying to find a way to replicate outside of "let it run in production for about 2 hours...", once I can get more info I'll post here, it may help others.
